spring:
  datasource:
    url: jdbc:tc:postgresql:15-alpine:///test-db
    username: test
    password: test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: comment_service
  flyway:
    enabled: true
    schemas: comment_service
    baseline-on-migrate: true
    locations: classpath:db/migration

  data:
    redis:
      host: localhost
      port: 6379

topic:
  comment-created: comment-created-event
  comment-removed: comment-removed-event
  post-removed: post-removed-event

eureka:
  client:
    enabled: false

post-service:
  url: http://post-service
