server:
  port: 8085

spring:
  application:
    name: comment-service
  datasource:
    url: jdbc:postgresql://comment-db:5432/comment_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: comment_service
  flyway:
    schemas: comment_service
    baseline-on-migrate: true
    locations: classpath:db/migration
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false
      spring.json.trusted.packages: "*"

topic:
  comment-created: comment-created-event
  comment-removed: comment-removed-event
  post-removed: post-removed-event

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

post-service:
  url: http://post-service:8081