server:
  port: 8086

spring:
  application:
    name: media-service
  datasource:
    url: jdbc:postgresql://media-db:5432/media_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: media_service
  flyway:
    schemas: media_service
    baseline-on-migrate: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

minio:
  url: http://localhost:8000
  access-key: minioadmin
  secret-key: minioadmin
  posts-bucket: posts-media
  profiles-bucket: profile-photos
  max-file-size: 10485760
  allowed-image-types:
    - image/jpeg
    - image/jpg
    - image/png
    - image/gif
    - image/webp
  allowed-video-types:
    - video/mp4
    - video/avi
    - video/mov

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
