server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices-db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: user_service
  flyway:
    schemas: user_service
    baseline-on-migrate: true
