services:

  media-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: media-service
    ports:
      - "8086:8086"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/media_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: media-service-db
    environment:
      POSTGRES_DB: media_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - media-db-data:/var/lib/postgresql/data

volumes:
  media-db-data: