services:

  feed-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feed-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/feed_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - postgres
      - redis
      - kafka
      - zookeeper

  postgres:
    image: postgres:15-alpine
    container_name: feed-service-db
    environment:
      POSTGRES_DB: feed_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54331:5432"
    volumes:
      - feed-db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4
    container_name: feed-service-redis
    ports:
      - "63795:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: feed-service-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: feed-service-kafka
    depends_on:
      - zookeeper
    ports:
      - "9097:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  feed-db-data: