services:
  postgres:
    image: postgres:16
    container_name: postgres_user_service
    environment:
      POSTGRES_DB: ${DOCKER_DATABASE_DB}
      POSTGRES_USER: ${DOCKER_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DOCKER_DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend: