server:
  port: 8083

spring:
  application:
    name: like-service
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices-db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: like_service
  flyway:
    schemas: like_service
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

post-service:
  url: http://user-service:8081