spring:
  datasource:
    url: jdbc:tc:postgresql:15-alpine:///test-db
    username: test
    password: test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: like_service
  flyway:
    enabled: true
    schemas: like_service

  data:
    redis:
      host: localhost
      port: 6379

topic:
  like-sent: like-sent-event
  like-removed: like-removed-event
  post-removed: post-removed-event

eureka:
  client:
    enabled: false
